/*
 * CLCD_program.c
 *
 *  Created on: Aug 5, 2023
 *      Author: Obiid
 */


#include "../../LIB/STD_TYPES.h"
#include "../../LIB/BIT_MATH.h"

#ifndef	F_CPU
#define F_CPU 8000000
#endif
#include <util/delay.h>

#include "../../MCAL/DIO/DIO_interface.h"

#include "STEPPERMOTOR_config.h"
#include "STEPPERMOTOR_private.h"
#include "STEPPERMOTORCLCD_interface.h"


void STEPPERMOTOR_voidInit(void){

	DIO_voidSetPinDirection(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_OUTPUT);

	DIO_voidSetPinDirection(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_OUTPUT);
	DIO_voidSetPinDirection(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_OUTPUT);
	DIO_voidSetPinDirection(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_OUTPUT);

}
void STEPPERMOTOR_voidRotCW(u16 degrees){


	for(u16 iterations = 0 ; iterations < ((64 * degrees) /45); iterations++ ){
		//step 1
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_LOW );
		_delay_ms(10);
		
		
		//step 2
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_HIGH );
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_LOW);
		_delay_ms(10);

		//step 3
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_LOW);
		_delay_ms(10);


		//step 4

		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_HIGH);
		_delay_ms(10);

	}



}

void STEPPERMOTOR_voidRotCCW(u16 degrees){

	for(u16 iterations = 0 ; iterations < ((64 * degrees) /45); iterations++ ){
	
		//step 4

		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_LOW);
		_delay_ms(10);

		//step 3
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_HIGH);
		_delay_ms(10);

		//step 2
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_HIGH);
		_delay_ms(10);

			//step 1
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_PINK_PIN , DIO_LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_BLUE_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_YELLOW_PIN , DIO_HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT, STEPPERMOTOR_ORANGE_PIN , DIO_HIGH);
		
		_delay_ms(10);

		
	}





}

