#ifndef HAL_STEPPERMOTOR_CONFIG_H_
#define HAL_STEPPERMOTOR_CONFIG_H_



#define STEPPERMOTOR_PINK_PIN       0
#define STEPPERMOTOR_BLUE_PIN       1
#define STEPPERMOTOR_YELLOW_PIN     2
#define STEPPERMOTOR_ORANGE_PIN     3

#define STEPPERMOTOR_PORT       DIO_PORTB


#endif /* HAL_CLCD_CLCD_CONFIG_H_ */
